### ISSUE TITLE
Link

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/calendar#63]
https://github.com/GroceriStar/calendar/blob/master/src/components/Calendar/Meal.js#L26
https://github.com/GroceriStar/calendar/blob/master/src/components/Modals/ModalWork.js#L87-L91

**Comment by atherdon** [comment]
@GuiFSs this is a small task too. you can see it duplicated at `groceristar-frontend` project too

**Comment by GuiFSs** [comment]
@atherdon  can you explain me how do you want it to be? because i don't see a good way to move links to another component

**Comment by atherdon** [comment]
hmm, looks like we solve it :)
Sorry for taking your time on it.

Main idea was to replace <a> tag with <Link> component from react-dom

**Comment by atherdon** [comment]
closing it
